version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: "/bin/sh -c 'bun i && bun start:dev'"
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./tmp/mongodata:/data/db

volumes:
  mongo_data:
